carts/urls.py
from django.conf.urls import url

from .views import cart_home, cart_update, checkout_home, checkout_done_view

urlpatterns = [
    url(r'^$', cart_home,name='home'),
    url(r'^update/$', cart_update, name='update'),
    url(r'^checkout/$', checkout_home, name='checkout'),
    url(r'^checkout/success$', checkout_done_view, name='success'),
]


#superuser
#admin
#admin@admin.com
#asdf1234

ecommerce/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
from django.contrib.auth.views import LogoutView

# from products.views import (ProductListView, productlistview,ProductDetailView, productdetailview,
#     ProductFeaturedListView,ProductFeaturedDetailView,ProductDetailSlugView)

from accounts.views import LoginView,RegisterView,guest_register_view
from .views import home_page,contact_page,about_page
from addresses.views import checkout_address_create_view, checkout_address_reuse_view
from carts.views import cart_detail_api_view
from billing.views import payment_method_view,payment_method_createview
from marketing.views import MarketingPreferenceUpdateView, MailchimpWebhookView


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', home_page, name='home'),
    url(r'^about/$', about_page,name='about'),
    url(r'^contact/$', contact_page,name='contact'),
    url(r'^login/$', LoginView.as_view(),name='login'),
    url(r'^checkout/address/create/$',checkout_address_create_view,name='checkout_address_create'),
    url(r'^checkout/address/reuse/$',checkout_address_reuse_view,name='checkout_address_reuse'),
    url(r'^register/guest/$', guest_register_view,name='guest_register'),
    url(r'^logout/$', LogoutView.as_view(),name='logout'),
    url(r'^products/', include("products.urls",namespace = 'products')),
    url(r'^api/cart/$', cart_detail_api_view,name='api-cart'),
    url(r'^cart/', include("carts.urls",namespace = 'cart')),
    url(r'^register/$', RegisterView.as_view(),name='register'),
    url(r'^bootstrap/$', TemplateView.as_view(template_name = 'bootstrap/example.html')),
    url(r'^search/', include("search.urls",namespace = 'search')), 
    url(r'^settings/email/',MarketingPreferenceUpdateView.as_view(), name='marketing-pref'),   
    url(r'^webhooks/mailchimp/',MailchimpWebhookView.as_view(), name='webhooks-mailchimp'),   
    url(r'^billing/payment-method/create/',payment_method_createview,name='billing-payment-method-endpoint'),
    url(r'^billing/payment-method/',payment_method_view,name='billing-payment-method'),

    # url(r'^product-fbv/$', productlistview),
    # url(r'^featured/$', ProductFeaturedListView.as_view()),
    # url(r'^featured/(?P<pk>\d+)/$', ProductFeaturedDetailView.as_view()),
    # url(r'^products/$', ProductListView.as_view()),
    # url(r'^product-fbv/(?P<pk>\d+)/$', productdetailview),
    # #url(r'^products/(?P<pk>\d+)/$', ProductDetailView.as_view()),
    # url(r'^products/(?P<slug>[\w-]+)/$', ProductDetailSlugView.as_view()),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#superuser
#admin
#admin@admin.com
#asdf1234

'''
<!-- <p>Cart Items: {% for product in object.cart.products.all %} {{ product }} {% if not forloop.last %}, {% endif %} {% endfor %}</p> -->
'''

products/urls.py
from django.conf.urls import url

from products.views import (ProductListView,ProductDetailSlugView)


urlpatterns = [
    url(r'^$', ProductListView.as_view(),name='list'),
    url(r'^(?P<slug>[\w-]+)/$', ProductDetailSlugView.as_view(), name='detail'),
]


#superuser
#admin
#admin@admin.com
#asdf1234

templates/base/css.html
{% load static %}

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<link rel="stylesheet" href='{% static "css/main.css" %}' >

<!-- Font awesome -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" >

<!-- Jquery Confirm -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.0/jquery-confirm.min.css">

<!-- Jquery Confirm -->
<link rel="stylesheet" href="{% static 'css/stripe-style.css' %}">

templates/base/forms.html
{% extends "base.html" %}





{% block content %}
<div class="col-12 col-md-6 mx-auto">
{% if title %}<h1 class="my-3">{{ title }}</h1>{% endif %}
<form method="POST" action="{% if action_url %}{{ action_url }}{% endif %}">{% csrf_token %}
	{% if next_url %}
	<input type='hidden' name='next' value="{{ next_url }}" />
	{% endif %}

	{{ form.as_p }}
	<button type="submit" class="btn btn-default">Save</button>
</form>
{% endblock %}

templates/base/js.html
{% load static %}

<script src="https://code.jquery.com/jquery-3.2.1.min.js" ></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>


<!-- stripe js -->
<script src="https://js.stripe.com/v3/"></script>

<!-- Jquery Confirm -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.0/jquery-confirm.min.js"></script>


<!-- js render -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jsrender/0.9.88/jsrender.min.js"></script>
{% include 'base/js_templates.html' %}

<!-- ecommerce csrf ajax js -->
<script src="{% static 'js/csrf_ajax.js' %}"></script>
<!-- ecommerce custom js -->
<script src="{% static 'js/ecommerce.js' %}"></script>

<!-- ecommerce custom2 js -->
<script src="{% static 'js/ecommerce.main.js' %}"></script>

templates/base/js_templates.html
{% verbatim %}
<!-- Stripe temmplate form -->
<script id="stripeTemplate" type="text/x-jsrender">
<form class='payment-form' action="/charge" method="post" id="payment-form" data-token='{{:publish_key}}' 		data-next-url='{{:next_url}}'>
  <div class="form-row">
    <!-- <label for="card-element">
      Credit or debit card
    </label> -->
    
    <div id="card-element" class="form-control">
      <!-- A Stripe Element will be inserted here. -->
    </div>

    <!-- Used to display form errors. -->
    <div id="card-errors" role="alert"></div>
  </div>

  <button class="btn btn-primary my-3 btn-load">{{:btn_title}}</button>
</form>
</script>

{% endverbatim %}

templates/base/navbar.html
{% url 'home' as home_url %}
{% url 'contact' as contact_url %}
{% url 'login' as login_url %}
{% url 'logout' as logout_url %}
{% url 'products:list' as list_url %}
{% url 'register' as register_url %}
{% url 'cart:home' as cart_url %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-3">
  <div class="container">
  <a class="navbar-brand" href="{{ home_url }}">
        <img src="https://getbootstrap.com/docs/4.0/assets/brand/bootstrap-solid.svg" width="30" height="30" class="d-inline-block align-top" alt="">
      {% if brand_name %}{{ brand_name }} {% else %} eCommerce{% endif %}</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item {% if request.path == home_url %}active{% endif %}">
        <a class="nav-link" href="{{ home_url }}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item {% if request.path == contact_url %}active{% endif %}">
        <a class="nav-link" href="{{ contact_url }}">Contact</a>
      </li>
      <li class="nav-item {% if request.path == list_url %}active{% endif %}">
        <a class="nav-link" href="{{ list_url }}">Products</a>
      </li>

      {% if request.user.is_authenticated %}

      <li class="nav-item {% if request.path == logout_url %}active{% endif %}">
        <a class="nav-link" href="{{ logout_url }}">Logout</a>
      </li>
      {% else %}
      <li class="nav-item {% if request.path == register_url %}active{% endif %}">
        <a class="nav-link" href="{{ register_url }}">Register</a>
      </li>
      <li class="nav-item {% if request.path == login_url %}active{% endif %}">
        <a class="nav-link" href="{{ login_url }}">Login</a>
      </li>
      {% endif %}
      <li class="nav-item {% if request.path == cart_url %}active{% endif %}">
        <a class="nav-link" href="{{ cart_url }}"><span class="navbar-cart-count">{{ request.session.cart_items }}</span> <i class="fa fa-shopping-cart" aria-hidden="true"></i></a>
      </li>
      <!-- <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li> -->
      
    </ul>
    {% include 'search/snippets/search-form.html' %}
  </div>
</div>
</nav>